#- platform: generic
#  name: Weather
#  still_image_url: https://192.168.1.68:8443/OV2680/poll.php?thumb=yes&dummy=1512056489315
- platform: mjpeg
  name: "Living Room"
  username: hass
  password: l1st3n2ME 
  mjpeg_url: http://192.168.1.19:8081
