jarvis:
  module: jarvis
  class: jarvis
  # core
  snips_mqtt_host: '192.168.1.19'

  #media players
  # these are mapped to siteIds in snips
  # to mute players in a specific room only
  media_player:
    default: media_player.snapcast_client_6152618a83b04b70b879e3fa1f4664b2
    bonus: media_player.snapcast_client_4b8c047b8b04d3bb68c2b07e00000005
    remote: media_player.snapcast_client_45f086e40e8f48a7852eff4fd78d81ea

  # music
  mopidy_host: '192.168.1.201'

  # speech
  speech_file: /jarvis/data/speech_en.yml
