- platform: broadlink
  host: 192.168.1.53
  mac:  34:ea:34:4a:29:14
  switches:
    panasonic_tv:
      friendly_name: 'Panasonic Plasma Power'
      command_on: JgAyAXM5Dw4OKw8ODg4PDg4PDg4PDg4ODw4ODw4ODw4OKw8ODg4PDg4PDg4PDg4ODw4PDg4rDg8ODg8ODg4PDg8ODg4PDg4rDw4OKw4rDyoPKw4ODw4OKw8ODisPKg8qDysODw4rDgAJrnM5Dg8OKw4ODw4PDg4ODw4ODg8ODw4ODg8ODg8OKw4ODw4PDg4ODw4ODw4ODw4ODg8rDg4PDg4PDg4PDg4ODw4ODw4rDg4PKw4rDisPKg8ODw4OKw4PDisOKw4rDyoPDg8qDwAJrXQ4Dw0QKg8NEA0PDg8NEA0PDRANDw4PDRANDw0QKg8NEA0PDg8NEA0PDRANDw4PDRApEA0QDQ8NEA0PDg8NEA0PDRAqDw0QKg8qDyoPKhANDw4PKg8NECoPKg8qDyoQDQ8qEAANBQAAAAAAAA==
      command_off: JgAyAXM5Dw4OKw8ODg4PDg4PDg4PDg4ODw4ODw4ODw4OKw8ODg4PDg4PDg4PDg4ODw4PDg4rDg8ODg8ODg4PDg8ODg4PDg4rDw4OKw4rDyoPKw4ODw4OKw8ODisPKg8qDysODw4rDgAJrnM5Dg8OKw4ODw4PDg4ODw4ODg8ODw4ODg8ODg8OKw4ODw4PDg4ODw4ODw4ODw4ODg8rDg4PDg4PDg4PDg4ODw4ODw4rDg4PKw4rDisPKg8ODw4OKw4PDisOKw4rDyoPDg8qDwAJrXQ4Dw0QKg8NEA0PDg8NEA0PDRANDw4PDRANDw0QKg8NEA0PDg8NEA0PDRANDw4PDRApEA0QDQ8NEA0PDg8NEA0PDRAqDw0QKg8qDyoPKhANDw4PKg8NECoPKg8qDyoQDQ8qEAANBQAAAAAAAA==
