- platform: mqtt
  name: coffee_power
  state_topic: 'jarvis/coffeeOut/state'
  value_template: '{{ value_json.power }}'
  hidden: true
- platform: mqtt
  name: coffee_heat
  state_topic: 'jarvis/coffeeOut/state'
  value_template: '{{ value_json.heat }}'
  hidden: true
- platform: mqtt
  name: coffee_empty
  state_topic: 'jarvis/coffeeOut/state'
  value_template: '{{ value_json.empty }}'
  hidden: true
