- alias: Back Door Open
  trigger:
    - entity_id: binary_sensor.visonic_mct340_e_0b0023ed_1
      from: 'off'
      platform: state
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.vincent_home
      state: 'on'
  action:
    - alias: 'Alert for Back Door Open to Tods iPhone'
      data:
        message: 'Back Door Open'
      service: notify.ios_tods_iphone

#alias: Back Door Closed
#trigger:
#  - entity_id: binary_sensor.smartthings_multiv4_01042e9f_1
#    from: 'on'
#    platform: state
#    to: 'off'
#condition:
#  - condition: state
#    entity_id: input_boolean.vincent_home
#    state: true
#action:
#  - alias: Alert for Back Door Closed to Tods iPhone
#    data:
#      message: Back Door Closed
#    service: notify.ios_tods_iphone
