- alias: jarvis_hotword_toggle
  trigger:
    platform: mqtt
    topic: hermes/hotword/#
  action:
    event: JARVIS_MQTT
    event_data_template:
      topic: '{{ trigger.topic }}'
      payload: '{{ trigger.payload }}'

- alias: jarvis_intent
  trigger:
    platform: mqtt
    topic: hermes/intent/#
  action:
    event: JARVIS_MQTT
    event_data_template:
      topic: '{{ trigger.topic }}'
      payload: '{{ trigger.payload }}'

######################################

- alias: lightsTurnOnSet
  trigger:
    platform: mqtt
    topic: hermes/intent/user_rZEKlr8M7M3__lightsTurnOnSet
  action:
    event: JARVIS_LIGHTS_ON
    event_data_template:
      payload: '{{ trigger.payload }}'

- alias: lightsTurnOff
  trigger:
    platform: mqtt
    topic: hermes/intent/user_rZEKlr8M7M3__lightsTurnOff
  action:
    event: JARVIS_LIGHTS_OFF
    event_data_template:
      payload: '{{ trigger.payload }}'

- alias: setThermostat
  trigger:
    platform: mqtt
    topic: hermes/intent/user_rZEKlr8M7M3__setThermostat
  action:
    event: JARVIS_THERMOSTAT
    event_data_template:
      payload: '{{ trigger.payload }}'

- alias: intentNotRecognized
  trigger:
    platform: mqtt
    topic: hermes/nlu/intentNotRecognized
  action:
    event: JARVIS_INTENT_NOT_RECOGNIZED
    event_data_template:
      payload: '{{ trigger.payload }}'

- alias: TSchmidty:YesNoResponse
  trigger:
    platform: mqtt
    topic: hermes/intent/TSchmidty:YesNoResponse
  action:
    event: JARVIS_YESNO_RESPONSE
    event_data_template:
      payload: '{{ trigger.payload }}'

- alias: TSchmidty:tellJoke
  trigger:
    platform: mqtt
    topic: hermes/intent/TSchmidty:tellJoke
  action:
    event: JARVIS_SAY
    event_data_template:
      payload: '{{ trigger.payload }}'
      type: 'joke'

- alias: TSchmidty:playTVShow
  trigger:
    platform: mqtt
    topic: hermes/intent/TSchmidty:playTV
  action:
    event: JARVIS_TV
    event_data_template:
      payload: '{{ trigger.payload }}'
