- alias: hotwordDetected
  trigger:
    platform: mqtt
    topic: hermes/hotword/toggleOff
  action:
    event: JARVIS_LISTENING

- alias: asrStopListening
  trigger:
    platform: mqtt
    topic: hermes/hotword/toggleOn
  action:
    event: JARVIS_NOT_LISTENING

- alias: lightsTurnOnSet
  trigger:
    platform: mqtt
    topic: hermes/intent/user_rZEKlr8M7M3__lightsTurnOnSet
  action:
    event: JARVIS_LIGHTS_ON
    event_data_template:
      payload: '{{ trigger.payload }}'

- alias: lightsTurnOff
  trigger:
    platform: mqtt
    topic: hermes/intent/user_rZEKlr8M7M3__lightsTurnOff
  action:
    event: JARVIS_LIGHTS_OFF
    event_data_template:
      payload: '{{ trigger.payload }}'

- alias: setThermostat
  trigger:
    platform: mqtt
    topic: hermes/intent/user_rZEKlr8M7M3__setThermostat
  action:
    event: JARVIS_THERMOSTAT
    event_data_template:
      payload: '{{ trigger.payload }}'

- alias: intentNotParsed
  trigger:
    platform: mqtt
    topic: hermes/nlu/intentNotParsed
  action:
    event: JARVIS_INTENT_NOT_PARSED
    event_data_template:
      payload: '{{ trigger.payload }}'
