- alias: Kitchen Door Open
  trigger:
    - entity_id: binary_sensor.visonic_mct340_e_0b111ae3_1
      from: 'off'
      platform: state
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.vincent_home
      state: 'on'
  action:
    - alias: 'Alert for Kitchen Door Open to Tods iPhone'
      data:
        message: 'Kitchen Door Open'
      service: notify.ios_tods_iphone
