- alias: Turn on Christmas Lights
  trigger:
    - platform: time
      at: '06:30'
  action:
    - service: switch.turn_on
      entity_id: switch.unknown_id0312_unknown_type0221_id251c_switch_3

- alias: Turn off Christmas Lights
  trigger:
    - platform: time
      at: '08:00'
  action:
    - service: switch.turn_off
      entity_id: switch.unknown_id0312_unknown_type0221_id251c_switch_3

- alias: Turn on Christmas Lights Evening
  trigger:
    - platform: time
      at: '16:00'
  action:
    - service: switch.turn_on
      entity_id: switch.unknown_id0312_unknown_type0221_id251c_switch_3

- alias: Turn off Christmas Lights Evening
  trigger:
    - platform: time
      at: '22:45'
  action:
    - service: switch.turn_off
      entity_id: switch.unknown_id0312_unknown_type0221_id251c_switch_3

- alias: Turn off Lights if we are not home
  trigger:
    - platform: state
      entity_id: group.household
      to: 'not_home'
  action:
    - service: switch.turn_off
      entity_id: group.living_room_lights
